name: Run Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Test Dependencies
      shell: bash
      run: sudo apt install -y libboost-test-dev libboost-serialization-dev

    - name: Create Local Config
      shell: bash
      run: ./configure test

    - name: Configure CMake
      shell: bash
      run: ./configure test

    - name: Build and Install
      shell: bash
      run: sudo make --build build-test --target install
      
    - name: Run LdConfig
      shell: bash
      run: sudo ldconfig

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make test
