name: Run Tests Windows

on: [push, pull_request]

jobs:

  test:
    name: Run tests Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSYS2
      # You may pin to the exact commit or the version.
      # uses: msys2/setup-msys2@e00cc7ca871a28b4d575714454769e57342da3da
      uses: msys2/setup-msys2@v2
      with:
        # Install packages after installation through pacman
        install: mingw-w64-x86_64-boost mingw-w64-x86_64-cmake

    - name: Build and Run Tests
      run: |
          ./configure test
          ./configure test
          cd build-test
          make install
          make test
